### PR TITLE
Added Docker image build Action

### PR DESCRIPTION
**Pull request by smark-d**
Added Dockerfile and Github Action (docker-publish.yml)

You need to set your DockerHub username and password in Repository secrets, username: DOCKERHUB_USERNAME, password: DOCKERHUB_TOKEN.

### CODE REVIEW

**Comment by smark-d** [comment]
Likewise, I hope you'll take the time to make some optimizations to the code to improve performance and readability, thanks!

**Comment by xiaozhou26** [comment]
Yes, thanks for submitting pull

**Comment by xiaozhou26** [comment]
I noticed that you know a lot about rust, you could try rust refactoring it

**Comment by xiaozhou26** [comment]
> Likewise, I hope you'll take the time to make some optimizations to the code to improve performance and readability, thanks!

**Pull request merged**
